#!/bin/bash

# Quick FBX to GLB Converter Script
# This will help you convert the Volvo S90 model

echo "🚗 Converting Volvo S90 to GLB format..."
echo ""
echo "Option 1: Online Converter (Easiest)"
echo "=================================="
echo "1. Go to: https://products.aspose.app/3d/conversion/fbx-to-gltf"
echo "2. Upload: public/models/Volvo S90/Volvo S90.fbx"
echo "3. Click 'Convert'"
echo "4. Download the result"
echo "5. Save as: public/models/car.glb"
echo ""
echo "Option 2: Using Blender"
echo "======================="
echo "1. Install Blender: https://www.blender.org/"
echo "2. Open Blender"
echo "3. File → Import → FBX"
echo "4. Select: public/models/Volvo S90/Volvo S90.fbx"
echo "5. File → Export → glTF 2.0 (.glb)"
echo "6. Export as: public/models/car.glb"
echo ""
echo "Option 3: Download Better Model"
echo "==============================="
echo "Game-Ready Car (Recommended):"
echo "https://sketchfab.com/3d-models/low-poly-racing-car-dd9c0ba1f6d34ad6a42e09e57c3e59f9"
echo ""
echo "After conversion, run: npm run dev"
echo "Then visit: http://localhost:3000"
echo ""
echo "✅ The system will automatically load the new model!"
