# Gateway-specific configuration
server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: eureka-dashboard
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: config-server
          uri: http://localhost:8761
          predicates:
            - Path=/config/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
